### ISSUE TITLE
Factor out actual shutdown code out into a separate function from terminate

### ISSUE THREAD

**Issue by DrItanium** [pimoroni/UnicornHat#17]
I'm writting a Go wrapper around the ws2812-RPi C library for the unicorn hat and it seems that exit always called. This is potentially a bad thing for a language like Go since it can't shutdown cleanly (basically the rug is pulled out from under Go). While I already factored out the code into a separate C function for my Go library, would it be possible to do the same thing in the official C libraries to prevent duplication of effort?

**Comment by Gadgetoid** [comment]
I've, hopefully, fixed this problem and your other issue by removing the exit() call from terminate() altogether. This makes sense, I think, since Python should also use its own exit rather than, as you rightfully say, have the rug pulled from under it!
